name: yuktidea
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  cached_network_image: ^3.3.1
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  connectivity_plus: ^6.0.2
  fluttertoast: ^8.2.5
  http: ^1.2.1
  another_flushbar: ^1.12.30
  dartz: ^0.10.1
  skeletonizer: ^1.1.1
  intl: ^0.19.0
  flutter_neumorphic_plus: ^3.3.0
  carousel_slider: ^4.2.1
  flutter_svg: ^2.0.10+1
  pinput: ^4.0.0
  flutter_html: ^3.0.0-beta.2
  loading_animation_widget: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true
  assets:
   - assets/
   - assets/images/
   - assets/icons/

  fonts:
    - family: Metropolis
      fonts:
        - asset: assets/fonts/Metropolis-SemiBold.otf
          weight: 600
        - asset: assets/fonts/Metropolis-Regular.otf
          weight: 400
        - asset: assets/fonts/Metropolis-Light.otf
          weight: 400
        - asset: assets/fonts/Metropolis-Medium.otf
          weight: 500

